language: php

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: TYPO3_VERSION=^8
        - php: 7.2
          env:
            - TYPO3_VERSION=^8
            - COVERAGE=true
        - php: 7.1
          env: TYPO3_VERSION=^9
        - php: 7.2
          env: TYPO3_VERSION=^9

cache:
    directories:
        - $HOME/.composer/cache


before_script:
    - composer require typo3/minimal=$TYPO3_VERSION
    - git checkout composer.json

script:
    - .Build/bin/phpunit --coverage-text --coverage-clover=coverage.clover


after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi