language: php

matrix:
    fast_finish: true
    include:
        - php: 7.2
        - php: 7.3

cache:
    directories:
        - $HOME/.composer/cache


before_script:
    - git checkout composer.json


install:
  - travis_retry composer update --prefer-dist

script:
    - .Build/bin/phpunit --coverage-text --coverage-clover=coverage.clover


after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi